### ISSUE TITLE
Release setup

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/conda-adapter#14]
Let's setup release process for this repository.

**Comment by olenagerasimova** [comment]
@g4s8 could you please help with release process?

**Comment by g4s8** [comment]
@olenagerasimova done https://github.com/artipie/conda-adapter/commit/57bfe75bd0ab2b3aca6e338b4c6268502c45ce25 please try to push a tag to master branch

**Comment by olenagerasimova** [comment]
@g4s8 thanks
